using System.ComponentModel.DataAnnotations;

namespace COMSATS.StudentPortal.Web.Models.Domain;

public class CourseOffering { public int Id { get; set; } public int CourseId { get; set; } public Course? Course { get; set; } public int TeacherProfileId { get; set; } public TeacherProfile? Teacher { get; set; } [MaxLength(40)] public string Term { get; set; } = string.Empty; [MaxLength(10)] public string Section { get; set; } = "A"; [MaxLength(60)] public string Room { get; set; } = string.Empty; public int Capacity { get; set; } = 40; public ICollection<Enrollment> Enrollments { get; set; } = new List<Enrollment>(); public ICollection<TimetableEntry> TimetableEntries { get; set; } = new List<TimetableEntry>(); public ICollection<AttendanceSession> AttendanceSessions { get; set; } = new List<AttendanceSession>(); public ICollection<AssessmentComponent> AssessmentComponents { get; set; } = new List<AssessmentComponent>(); }
public class AttendanceSession { public int Id { get; set; } public int CourseOfferingId { get; set; } public CourseOffering? CourseOffering { get; set; } public DateOnly SessionDate { get; set; } [MaxLength(30)] public string SessionType { get; set; } = "Lecture"; public int MarkedByTeacherProfileId { get; set; } public bool IsFinalized { get; set; } public ICollection<AttendanceRecord> Records { get; set; } = new List<AttendanceRecord>(); }
public class AttendanceRecord { public int Id { get; set; } public int AttendanceSessionId { get; set; } public AttendanceSession? Session { get; set; } public int StudentProfileId { get; set; } public StudentProfile? Student { get; set; } public AttendanceStatus Status { get; set; } public string? Remarks { get; set; } }
public class AssessmentComponent { public int Id { get; set; } public int CourseOfferingId { get; set; } public CourseOffering? CourseOffering { get; set; } [MaxLength(80)] public string Name { get; set; } = string.Empty; public int MaxMarks { get; set; } public decimal WeightPercent { get; set; } public DateOnly? DueDate { get; set; } public ICollection<StudentAssessmentResult> Results { get; set; } = new List<StudentAssessmentResult>(); }
public class StudentAssessmentResult { public int Id { get; set; } public int AssessmentComponentId { get; set; } public AssessmentComponent? Component { get; set; } public int StudentProfileId { get; set; } public StudentProfile? Student { get; set; } public int? MarksObtained { get; set; } public DateTime? GradedAt { get; set; } }
